### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by Diggsey** [jjpe/deltoid#1]
- The example in the readme doesn't compile. The derive now seems to be called "Delta" instead of "Deltoid".
- It's strange to require two crates: for example, with serde you just import `Serialize` from `serde` with the `derive` feature enabled, and then you can derive `Serialize`/`Deserialize`. `serde_derive` is an implementation detail that shouldn't be used directly by end-users.
- `#[derive(Delta)]` macro expands to code which references `serde_derive`. Instead, `deltoid` should re-export all names required by macros under a `deltoid::hidden` module so that only the `deltoid` crate name needs to be accessible in the macro scope.
- The derive macro itself is not documented, and it would be useful to add options like "opaque" (see https://docs.rs/serde-diff/0.4.1/serde_diff/derive.SerdeDiff.html for example)

**Comment by jjpe** [comment]
Hi, thanks for your interest in this crate!

Please create separate issues for each of those points.
This is because each of them needs to be dealt with separately.

**Comment by jjpe** [comment]
Closed this issue due to inactivity from OP.
